# Generated by Django 4.2.3 on 2023-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('player_position', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_cricket',
            },
        ),
        migrations.CreateModel(
            name='tbl_football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('player_position', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_football',
            },
        ),
    ]
